networks:
  backend-network:
services:
  nc-bot:
    platform: linux/amd64
    container_name: nc-bot-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "8501:8501"
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8000M
        reservations:
          cpus: '2.0'
          memory: 8000M