version: '3.8' # or whatever version you're using

services:

  nc-bot:
    platform: linux/amd64
    container_name: nc-bot-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "8501:8501"
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8000M
        reservations:
          cpus: '2.0'
          memory: 8000M

  postgres:
    container_name: pgvector_container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data
    build:
      context: .
      dockerfile: pg_vector/Dockerfile
    volumes:
       - db:/var/lib/postgresql/data
       - ./pg_vector/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: test
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network: 

volumes:
  db:
    driver: local
