networks:
  backend-network:
services:
  nc-bot:
    container_name: nc-bot-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "8501:8501"
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - backend-network
  