services:
  postgres:
    container_name: pgvector_container
    environment:
      POSTGRES_PASSWORD: your_password_123!
      PGDATA: /var/lib/postgresql/data
    build:
      context: .
      dockerfile: pg_vector/Dockerfile
    volumes:
       - db:/var/lib/postgresql/data
       - ./pg_vector/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: your_password_123!
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:

volumes:
    db:
      driver: local
